import Link from 'next/link';
import Image from 'next/image';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms',
  description: 'The short version of what using Cvly means, kept plain on purpose.',
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[var(--bg)]">
      <header className="border-b border-[var(--line)]">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <Image src="/logo.png" alt="Cvly" width={28} height={26} className="rounded-md" />
            <span className="text-[17px] font-bold tracking-[-0.02em]">Cvly</span>
          </Link>
          <Link href="/" className="text-sm text-[var(--muted)] hover:text-[var(--ink)] transition">← Back</Link>
        </div>
      </header>

      <div className="max-w-2xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-semibold tracking-tight mb-2">Terms</h1>
        <p className="text-sm text-[var(--muted)] mb-10">Last updated July 2026. Kept short on purpose.</p>

        <div className="space-y-8 text-sm leading-relaxed text-[var(--ink)]/85">
          <section>
            <h2 className="font-semibold text-base mb-2">What Cvly is</h2>
            <p>A free tool, currently in beta, that scores your resume against a job description and helps you improve it. Results are generated by AI and are meant as guidance, not a guarantee of any outcome.</p>
          </section>
          <section>
            <h2 className="font-semibold text-base mb-2">Accuracy</h2>
            <p>We aim for useful, honest results, but AI-generated content can be wrong. Always review anything Cvly generates — a rewrite, a cover letter, an interview answer hint — before you use it for a real application.</p>
          </section>
          <section>
            <h2 className="font-semibold text-base mb-2">Your content</h2>
            <p>You own what you paste into Cvly. We use it only to generate your results, as described in our <Link href="/privacy" className="text-[var(--accent-ink)] underline">privacy page</Link>.</p>
          </section>
          <section>
            <h2 className="font-semibold text-base mb-2">Beta status</h2>
            <p>Cvly is actively being built. Features may change, and free access during beta isn&apos;t a promise of free access forever — we&apos;ll be upfront if and when that changes.</p>
          </section>
        </div>
      </div>
    </main>
  );
}
